// Shared seed content for Wisdom Mode (hand-written, never AI-generated at runtime).

export const CATEGORIES = [
  { slug: "studies-work", emoji: "📚", name: "Studies & Work", order: 1,
    description: "Focus, deadlines, pressure and the discipline of doing the work." },
  { slug: "self-growth", emoji: "🌱", name: "Self Growth", order: 2,
    description: "Becoming who you are meant to be, one honest choice at a time." },
  { slug: "relationships", emoji: "🤝", name: "Relationships", order: 3,
    description: "Connection, distance, trust, and the courage to be seen." },
  { slug: "life-challenges", emoji: "🌗", name: "Life Challenges", order: 4,
    description: "Uncertainty, loss, and finding meaning when the path is dark." },
];

export const WISDOM = [
  { slug: "procrastination", category: "studies-work", title: "The Weight of the Undone", popular: true, featured: true,
    problem: "I know what I should do, but I keep delaying it.",
    tags: "procrastination,delay,avoidance,motivation,start,later,studies,work",
    wisdom: "Procrastination is rarely about laziness. It is almost always about fear wearing a quieter mask. You are not avoiding the task — you are avoiding the feeling the task threatens to produce: the possibility of doing it badly, the discomfort of beginning before you feel ready, the silence of effort without applause.\n\nNotice that the task itself never grows heavier. What grows is the story you carry about it. Each hour of delay adds another layer of dread, until a thirty-minute job feels like a mountain. The mountain is made of waiting, not of work.\n\nThe ancients knew that the will is not summoned by thinking — it is summoned by motion. You do not wait to feel ready and then act. You act, and readiness arrives behind you like a shadow catching up.",
    shift: "You are not behind because you are lazy. You are stuck because you are trying to feel ready before you begin. Readiness is the reward of starting, not its requirement.",
    action: "Set a timer for five minutes and do only the first, smallest piece of the task. When the timer ends, you may stop. You almost never will.",
    questions: ["What exactly am I avoiding — the task, or the feeling it brings?", "What is the smallest possible next step?", "What would I do if I trusted that starting badly is allowed?"],
    related: "fear-of-failure,overthinking,discipline,lack-of-focus" },

  { slug: "fear-of-failure", category: "studies-work", title: "The Courage to Be a Beginner", popular: true, featured: true,
    problem: "I am so afraid of failing that I would rather not try at all.",
    tags: "fear,failure,perfectionism,risk,trying,beginner",
    wisdom: "The fear of failure is the fear of a verdict — that if you try and fall short, the result will be a final sentence passed on who you are. But failure is never a verdict. It is information. It is the universe answering a question you were brave enough to ask.\n\nWhen you refuse to try, you imagine you are staying safe. In truth you have already chosen a guaranteed failure over a possible one. The unlived attempt is the only failure that cannot teach you anything.\n\nEvery master you admire was once clumsy. The difference between them and the person who quit is not talent — it is their willingness to be bad at something long enough to become good.",
    shift: "Failure is not the opposite of success; it is part of its architecture. You are not risking who you are — you are discovering who you can become.",
    action: "Choose one thing you have avoided out of fear and do a low-stakes version of it today, where the only goal is to participate, not to win.",
    questions: ["What am I afraid will happen if I fail?", "Whose verdict am I really afraid of?", "What would I attempt if I knew failure was simply data?"],
    related: "procrastination,self-doubt,confidence,failure" },

  { slug: "overthinking", category: "studies-work", title: "The Mind That Will Not Rest", popular: true,
    problem: "I replay everything in my head until I am exhausted by my own thoughts.",
    tags: "overthinking,rumination,anxiety,analysis,worry,thoughts",
    wisdom: "Overthinking feels like problem-solving, but it is its imitation. Real thinking moves toward a decision; overthinking circles a decision without ever landing. It mistakes motion for progress and exhaustion for effort.\n\nThe mind that overthinks believes that if it considers every angle, it can guarantee a safe outcome. But certainty is not something thinking can purchase. Some answers only arrive through living, not through rehearsing.\n\nThere is a quiet power in deciding that a thought has been thought enough. Not every question deserves a thousand visits. Sometimes the wisest act is to set the question down and let your hands do what your head cannot resolve.",
    shift: "You are not thinking your way to safety — you are thinking your way to exhaustion. Clarity comes from action, not from one more lap around the same thought.",
    action: "Write the looping thought on paper, then write one small action you can take about it. Do the action; close the loop on the page.",
    questions: ["Am I solving a problem or rehearsing a fear?", "What decision is this thought avoiding?", "What would change if I trusted myself to handle the outcome?"],
    related: "anxiety,procrastination,uncertainty,fear-of-future" },

  { slug: "burnout", category: "studies-work", title: "When the Well Runs Dry",
    problem: "I have pushed so hard for so long that I feel completely empty.",
    tags: "burnout,exhaustion,rest,overwork,tired,empty",
    wisdom: "Burnout is not weakness — it is the bill arriving for a debt you took on quietly, day after day, by giving more than you received. The body and mind are not machines; they are gardens, and even the most fertile soil must lie fallow to bear fruit again.\n\nYou were taught that rest must be earned, that stopping is a kind of failure. But rest is not the reward for work — it is part of the work. A bow drawn forever loses its power to send the arrow.\n\nRecovery does not begin with a grand escape. It begins with one honest sentence: I cannot keep doing this the way I have been. From that admission, a gentler rhythm can grow.",
    shift: "Rest is not the absence of productivity — it is the foundation of it. You are not lazy for needing to stop; you are human for having limits.",
    action: "Protect one hour today that asks nothing of you. No screens, no goals — just rest, fully permitted.",
    questions: ["What have I been giving that I never agreed to give?", "What would change if rest were allowed without guilt?", "What is one thing I can set down this week?"],
    related: "lack-of-focus,anxiety,meaninglessness,discipline" },

  { slug: "lack-of-focus", category: "studies-work", title: "The Scattered Light",
    problem: "My attention shatters into pieces and I cannot hold it on anything.",
    tags: "focus,attention,distraction,concentration,scattered",
    wisdom: "Attention is the rarest currency of your age, and a thousand forces compete to spend it for you. A scattered mind is not a broken mind — it is an untrained one, pulled in every direction because it was never taught to choose one.\n\nFocus is not forcing the mind to be still; it is gently returning it, again and again, to what matters. The returning is the practice. You do not fail at focus when your mind wanders — you practice it each time you bring it back.\n\nA single ray of sunlight passing through a lens can set wood aflame. The same light, scattered, only warms. Your power is not in how much attention you have, but in how narrowly you can aim it.",
    shift: "A wandering mind is not a flaw to fix but a habit to gently retrain. Focus is built one return at a time.",
    action: "Choose one task, remove one distraction completely, and work in a single 25-minute block with nothing else open.",
    questions: ["What is stealing my attention without my consent?", "What one thing deserves my focus right now?", "What would deep work feel like if I protected it?"],
    related: "overthinking,procrastination,discipline,exam-stress" },

  { slug: "exam-stress", category: "studies-work", title: "The Test Beyond the Test",
    problem: "The pressure of this exam feels like it will decide my entire worth.",
    tags: "exam,stress,pressure,test,study,grades",
    wisdom: "An exam measures what you knew on a single morning. It does not measure your intelligence, your future, or your value as a person. The mind under pressure forgets this and inflates one moment into a verdict on a whole life.\n\nStress is the body preparing for something it believes is dangerous. You can thank it for its loyalty and then remind it of the truth: this is a challenge, not a threat. Your survival does not depend on the outcome.\n\nPrepare with discipline, then release with trust. You are responsible for the effort, not for the guarantee. The calmest students are not those who care least, but those who have made peace with doing their best and letting the result be what it is.",
    shift: "The exam tests a slice of knowledge on one day — not your worth, not your future, not who you are.",
    action: "Make a short, realistic study plan for today, then schedule one deliberate break to remind your body it is safe.",
    questions: ["What story am I telling myself about what this exam decides?", "What is within my control, and what is not?", "How would I prepare if I trusted my own effort?"],
    related: "anxiety,fear-of-failure,overthinking,burnout" },

  { slug: "discipline", category: "self-growth", title: "The Architecture of the Will", popular: true, featured: true,
    problem: "I start strong but cannot stay consistent with anything.",
    tags: "discipline,consistency,habit,willpower,routine,commitment",
    wisdom: "Discipline is not a personality you are born with or without. It is a structure you build. People who appear disciplined have not won a war against themselves — they have arranged their lives so the right action is the easy one.\n\nMotivation is a guest; it visits and leaves. Discipline is the house you build so that even when the guest is gone, the work still happens. You do not rise to the level of your goals — you fall to the level of your systems.\n\nEach time you keep a small promise to yourself, you cast a vote for the person you are becoming. Consistency is not built in grand gestures but in unremarkable days where you simply did the thing again.",
    shift: "Discipline is not about feeling motivated — it is about designing a life where the right action requires the least willpower.",
    action: "Pick one keystone habit and shrink it until it feels almost too easy. Do that tiny version every day this week.",
    questions: ["Am I relying on motivation where I need a system?", "What is the smallest version of this habit I could never skip?", "What promise to myself do I most want to keep?"],
    related: "consistency,procrastination,confidence,lack-of-focus" },

  { slug: "confidence", category: "self-growth", title: "The Trust You Build in Yourself", popular: true,
    problem: "I doubt myself constantly and wait for permission to act.",
    tags: "confidence,self-belief,courage,self-worth,permission",
    wisdom: "Confidence is not the absence of doubt — it is the willingness to act while doubt is still present. The confident person is not certain; they have simply stopped waiting for certainty before they move.\n\nReal confidence is not borrowed from praise or stripped away by criticism. It is the quiet evidence you gather by keeping promises to yourself. Every time you do what you said you would, you become a little more trustworthy in your own eyes.\n\nYou have been waiting for permission that no one is coming to give. The authority you are looking for outside yourself has been yours to claim all along.",
    shift: "Confidence is not a feeling you wait for — it is a track record you build, one kept promise at a time.",
    action: "Do one small thing today that you have been waiting to feel ready for. Let the doing create the belief.",
    questions: ["Whose permission am I waiting for?", "What evidence of my own capability am I ignoring?", "What would I do today if I trusted myself fully?"],
    related: "self-doubt,fear-of-failure,identity-crisis,social-anxiety" },

  { slug: "self-doubt", category: "self-growth", title: "The Critic Within",
    problem: "A voice in my head insists I am not good enough.",
    tags: "self-doubt,inner critic,insecurity,not enough,comparison",
    wisdom: "The inner critic speaks in the voice of certainty, but it is rarely telling the truth. It is an old protector that learned, long ago, to keep you small so you would not risk being hurt. Its harshness is misguided care.\n\nYou are not obligated to believe every thought your mind produces. A thought is a suggestion, not a sentence. You can hear the critic, thank it for trying to keep you safe, and choose not to obey it.\n\nNotice how you would speak to a friend who felt as you do. That gentler voice is also yours. You are allowed to turn it toward yourself.",
    shift: "The voice saying you are not enough is not the truth — it is an old fear trying to protect you. You can listen without obeying.",
    action: "When the critic speaks today, write down its words, then write what you would say to a friend who felt that way.",
    questions: ["Where did this critical voice first come from?", "Would I speak to someone I love this way?", "What is one piece of evidence that contradicts the doubt?"],
    related: "confidence,identity-crisis,fear-of-failure,rejection" },

  { slug: "identity-crisis", category: "self-growth", title: "Becoming, Not Finding",
    problem: "I do not know who I am or who I am supposed to be anymore.",
    tags: "identity,self,crisis,who am i,meaning,change",
    wisdom: "The question \"who am I?\" assumes there is a fixed self waiting to be discovered, like a statue beneath the marble. But you are not a thing to be found — you are a process to be lived. Identity is not excavated; it is composed.\n\nConfusion about who you are is not a breakdown. It is often the soul outgrowing an old definition that no longer fits. The discomfort you feel is the gap between who you were and who you are becoming.\n\nYou do not need the whole map. You only need to notice what makes you feel most alive and most honest, and to take one step in that direction. Identity reveals itself in motion, not in stillness.",
    shift: "You are not failing to find yourself — you are in the middle of becoming. Identity is composed through living, not discovered through waiting.",
    action: "Name one value that feels unmistakably yours, and take one small action today that honors it.",
    questions: ["What old definition of myself am I outgrowing?", "When do I feel most like myself?", "What value would I refuse to abandon?"],
    related: "purpose,meaninglessness,confidence,self-doubt" },

  { slug: "purpose", category: "self-growth", title: "The Meaning You Make", popular: true,
    problem: "I feel lost, as if my life has no real direction or purpose.",
    tags: "purpose,meaning,direction,calling,lost,why",
    wisdom: "Purpose is not a single destiny hidden somewhere, waiting to be stumbled upon. It is not a lightning bolt. It is built, quietly, from the intersection of what moves you, what you are good at, and what the world around you needs.\n\nThe search for one grand purpose can paralyze you. But you do not need to know your life's meaning to live a meaningful day. Purpose is often discovered backward — you act, you contribute, and only later do you see the thread that connected it all.\n\nA life of meaning is not made of extraordinary moments. It is made of ordinary moments lived with attention, contribution, and care. The smallest act done with love already carries purpose within it.",
    shift: "Purpose is not found — it is built, one meaningful act at a time. You do not need your whole life's meaning to make today matter.",
    action: "Do one thing today that helps another person, however small, and notice how meaning follows contribution.",
    questions: ["What activities make me lose track of time?", "How do I want to be useful to others?", "What would a meaningful day look like, regardless of a grand purpose?"],
    related: "meaninglessness,identity-crisis,discipline,regret" },

  { slug: "consistency", category: "self-growth", title: "The Power of the Unremarkable Day",
    problem: "I can be intense for a few days, then I give up entirely.",
    tags: "consistency,habit,routine,discipline,daily,quit",
    wisdom: "You have been chasing intensity when what you needed was steadiness. Intensity feels heroic and burns out fast; consistency feels boring and changes everything. The river carves the canyon not with force but with return.\n\nThe all-or-nothing mind treats one missed day as total failure and uses it as permission to abandon the whole pursuit. But missing once is an event; missing twice is the beginning of a new pattern. Never miss twice.\n\nGreatness is not built on the days you feel inspired. It is built on the days you show up tired, unmotivated, and ordinary — and do a small amount anyway.",
    shift: "You do not need more intensity — you need to stop quitting. Consistency beats intensity because it compounds.",
    action: "Decide on a minimum version of your habit so small you can do it even on your worst day. Never miss twice.",
    questions: ["Am I confusing intensity with progress?", "What is my \"never miss twice\" minimum?", "What story do I tell myself after one missed day?"],
    related: "discipline,procrastination,confidence,burnout" },

  { slug: "rejection", category: "relationships", title: "When the Door Closes", popular: true,
    problem: "I was rejected and now I feel fundamentally unwanted.",
    tags: "rejection,heartbreak,unwanted,no,relationships,dating",
    wisdom: "Rejection feels like a statement about your worth, but it is almost always a statement about fit. A person, a job, a circle said \"not this, not now\" — and the wounded mind translates that into \"not ever, not anyone.\" That translation is a lie pain tells.\n\nNo one is wanted by everyone. The people you most admire have been turned away countless times. Rejection is not a sign you are unlovable — it is the unavoidable cost of being someone real enough to be chosen or not chosen.\n\nA door that closes was never going to lead where you belonged. The grief is real, but so is this: the right things rarely require you to shrink yourself to fit through a door that does not want you.",
    shift: "Rejection is information about fit, not a verdict on your worth. A closed door is redirection, not a sentence.",
    action: "Write down what the rejection actually said about fit, separate from the story it tells about your worth.",
    questions: ["What is this rejection actually about — me, or fit?", "What would I tell a friend who felt unwanted?", "What door might this closing be redirecting me toward?"],
    related: "loneliness,self-doubt,betrayal,social-anxiety" },

  { slug: "loneliness", category: "relationships", title: "The Ache of Disconnection", popular: true, featured: true,
    problem: "I feel deeply alone, even when I am around other people.",
    tags: "loneliness,isolation,alone,connection,belonging",
    wisdom: "Loneliness is not the absence of people — it is the absence of being seen. You can stand in a crowded room and ache, because what you long for is not company but recognition, the sense that someone knows the real you and stays.\n\nThe loneliest moments often carry a hidden invitation: to become, for yourself, the witness you have been waiting for. Solitude and loneliness are not the same. One is a wound; the other can become a home, once you learn to keep yourself company.\n\nConnection is built through small acts of courage — reaching out first, revealing something true, letting yourself be known before you are certain you will be accepted. The bridge to others begins on your side.",
    shift: "Loneliness is not a sign that something is wrong with you — it is a signal of a need for connection, and a quiet invitation to reach out.",
    action: "Reach out to one person today with something honest — not small talk, but a real word about how you actually are.",
    questions: ["Am I longing for company, or for being truly seen?", "What small act of reaching out could I risk today?", "How might I become better company for myself?"],
    related: "rejection,social-anxiety,attachment,meaninglessness" },

  { slug: "betrayal", category: "relationships", title: "The Broken Trust",
    problem: "Someone I trusted betrayed me, and I cannot stop reliving it.",
    tags: "betrayal,trust,broken,hurt,forgiveness,anger",
    wisdom: "Betrayal wounds twice: once in the act itself, and again every time you replay it. The mind returns to the scene trying to make it make sense, as if understanding it perfectly could undo the pain. But some acts are not yours to explain — they belong to the one who chose them.\n\nYou may believe that staying angry keeps you safe, that your resentment is a guard at the gate. But resentment guards nothing; it only keeps you tethered to the very person who hurt you. Forgiveness, when it comes, is not for them — it is the moment you set down a weight you were never meant to carry forever.\n\nTrust, once broken, can be rebuilt or released — but it cannot be forced. You are allowed to take your time, to protect yourself, and to let the betrayal teach you discernment without letting it harden you into permanent suspicion.",
    shift: "The betrayal was their choice, not your failure. Holding the anger does not punish them — it tethers you to them.",
    action: "Write the story of what happened once, fully, then choose to stop re-litigating it in your mind today.",
    questions: ["Whose choice was the betrayal — really?", "What is my resentment costing me?", "What would protecting myself without hardening look like?"],
    related: "rejection,attachment,regret,loneliness" },

  { slug: "attachment", category: "relationships", title: "Holding Without Gripping",
    problem: "I cling to people so tightly that I push them away.",
    tags: "attachment,clingy,anxiety,needy,relationships,fear",
    wisdom: "Anxious attachment is love distorted by fear — the fear that if you do not hold tightly enough, you will be left. But the tighter the grip, the more the other person feels the squeeze rather than the love, and the very thing you fear becomes more likely.\n\nThe cure for clinging is not to care less, but to build a self that does not collapse if the other person steps away. Security is an inside job. When you can be alone without falling apart, you can be together without grasping.\n\nLove offered from fullness feels like a gift. Love offered from fear feels like a demand. The work is to fill your own cup enough that your love becomes an offering rather than a plea.",
    shift: "The grip that comes from fear pushes away the very thing you are afraid to lose. Security is built within, not extracted from others.",
    action: "Spend time today doing something that fills your own cup, independent of anyone's attention or approval.",
    questions: ["What am I afraid will happen if I loosen my grip?", "Where does my sense of security currently live?", "How can I offer love from fullness rather than fear?"],
    related: "loneliness,rejection,self-doubt,jealousy" },

  { slug: "jealousy", category: "relationships", title: "The Mirror of Envy", popular: true,
    problem: "I feel consumed by jealousy when I see others succeed or get loved.",
    tags: "jealousy,envy,comparison,resentment,insecurity",
    wisdom: "Jealousy is painful, but it is also honest. It points, like a compass needle, straight at what you secretly want and fear you cannot have. Beneath every flash of envy is a desire you have not yet given yourself permission to pursue.\n\nComparison steals the present by measuring your inside against someone else's outside. You see their highlight and forget it sits atop struggles you will never witness. No one's life is the seamless story it appears to be.\n\nYou can transform envy into instruction. Instead of \"why them and not me,\" ask \"what does my reaction reveal that I long for?\" Then turn that longing into a direction rather than a wound.",
    shift: "Jealousy is not a flaw to hide but a signpost pointing at what you truly want. Let it inform your direction instead of poisoning your peace.",
    action: "When jealousy arises today, name the desire underneath it and write one step toward that desire.",
    questions: ["What does my jealousy reveal that I want?", "Am I comparing my inside to someone's outside?", "How can I turn this envy into a direction?"],
    related: "self-doubt,confidence,attachment,identity-crisis" },

  { slug: "social-anxiety", category: "relationships", title: "The Eyes You Imagine",
    problem: "I am terrified of being judged, so I avoid people altogether.",
    tags: "social anxiety,judgment,shy,fear,people,awkward",
    wisdom: "Social anxiety convinces you that everyone is watching and judging, when the truth is far kinder and far more humbling: most people are far too absorbed in their own self-consciousness to scrutinize yours. The spotlight you feel is one you are holding on yourself.\n\nThe fear predicts catastrophe — that you will be exposed, mocked, rejected. But these predictions are rarely tested, because avoidance keeps you safe and small. Each avoidance teaches the fear that it was right to be afraid.\n\nCourage in social spaces is not the absence of the racing heart. It is staying in the room while it races, and discovering, slowly, that you survived. The fear shrinks not when you wait for it to pass, but when you act before it does.",
    shift: "The harsh audience you imagine is mostly absorbed in their own self-consciousness. The spotlight is one you hold on yourself.",
    action: "Enter one social situation you would normally avoid and stay a few minutes longer than the fear wants you to.",
    questions: ["What catastrophe am I predicting, and how often does it come true?", "Is the spotlight real, or am I holding it on myself?", "What small social risk could I survive today?"],
    related: "confidence,self-doubt,loneliness,rejection" },

  { slug: "regret", category: "life-challenges", title: "Making Peace With the Past", popular: true,
    problem: "I am haunted by choices I made and cannot take back.",
    tags: "regret,past,mistakes,guilt,what if,choices",
    wisdom: "Regret judges your past self with the knowledge your present self has earned. But the person who made that choice did not have your hindsight. They acted with the awareness, the wounds, and the limits they had at the time. To condemn them is to punish someone for not knowing what they could not yet know.\n\nThe past cannot be edited, only interpreted. And the interpretation is yours to choose. A mistake can be a stain you carry or a teacher you thank. The event is fixed; its meaning is not.\n\nRegret only becomes useful when it points forward. If it teaches you how you want to live now, it has done its work. Beyond that, it is just self-punishment dressed as wisdom.",
    shift: "You judged your past self with knowledge they did not have. Regret is only useful when it teaches you how to live now.",
    action: "Write what your past mistake taught you, then write one way you will honor that lesson today.",
    questions: ["What did my past self not yet know?", "What has this regret actually taught me?", "How can I let this guide me forward instead of holding me back?"],
    related: "failure,meaninglessness,purpose,betrayal" },

  { slug: "uncertainty", category: "life-challenges", title: "Walking Into the Fog",
    problem: "I cannot bear not knowing how things will turn out.",
    tags: "uncertainty,unknown,control,future,fear,anxiety",
    wisdom: "The mind craves certainty the way the body craves water — it feels like survival depends on it. But certainty about the future has never actually existed; it is an illusion we cling to for comfort. Even on your calmest days, you never truly knew what tomorrow held.\n\nUncertainty is not the problem. The struggle to eliminate it is. When you stop demanding guarantees the world cannot give, a strange freedom appears: you only have to handle this step, not the entire unseen road.\n\nThe fog does not lift because you stare harder into it. It lifts as you walk. Clarity is not a prerequisite for movement — it is the result of it.",
    shift: "You were never actually promised certainty — you only believed you were. Peace comes not from knowing the future but from trusting you can meet it.",
    action: "Identify one thing within your control today and act on it; release one thing that is not.",
    questions: ["What certainty am I demanding that no one can give?", "What is the next single step I can actually take?", "What would change if I trusted myself to handle what comes?"],
    related: "fear-of-future,anxiety,overthinking,meaninglessness" },

  { slug: "failure", category: "life-challenges", title: "The Lessons in the Ruins",
    problem: "I failed at something important and feel like a failure as a person.",
    tags: "failure,defeat,loss,setback,identity,shame",
    wisdom: "There is a vast difference between failing and being a failure. The first is an event; the second is an identity. You experienced a loss — you did not become one. The mind quietly turns \"I failed\" into \"I am a failure,\" and that small shift in grammar can darken an entire life.\n\nEvery failure carries a curriculum, but only for those willing to study the ruins rather than flee them. The question is not \"why did this happen to me\" but \"what is this asking me to learn, to change, to release.\"\n\nThe people who eventually succeed are not those who never failed. They are those who failed and refused to let the failure define them. Defeat is only final when you stop extracting its lessons.",
    shift: "You experienced a failure — you did not become one. The event is over; its meaning is yours to decide.",
    action: "List one thing the failure taught you and one specific way you will apply that lesson next.",
    questions: ["Did I fail, or am I calling myself a failure?", "What is this failure trying to teach me?", "What would I attempt next if I knew failure was survivable?"],
    related: "fear-of-failure,regret,confidence,loss" },

  { slug: "fear-of-future", category: "life-challenges", title: "The Tomorrow That Frightens",
    problem: "I am paralyzed by anxiety about what the future holds.",
    tags: "fear,future,anxiety,worry,tomorrow,unknown",
    wisdom: "Fear of the future is the mind's attempt to suffer a thing before it has happened, as if rehearsing the pain could soften it. But worry is interest paid on a debt that may never come due. You can live a hundred imagined catastrophes and still meet only one real one.\n\nThe future you fear does not exist. It is a projection, a story, a forecast built from your anxieties rather than from facts. And here is what the anxious mind forgets: the future version of you will be wiser, more capable, and more resourced than you are now. You will not meet tomorrow as today's self.\n\nYou do not have to carry the whole future at once. It arrives one day at a time, and you have always, somehow, found a way to meet each day as it came.",
    shift: "You are suffering a future that does not exist yet. The you who meets it will be wiser and stronger than the you imagining it now.",
    action: "Bring your attention fully to one task in front of you today, and let the future remain where it is.",
    questions: ["What future am I suffering before it has happened?", "What evidence do I have that I can handle hard things?", "What is the one day I actually have to meet — today?"],
    related: "anxiety,uncertainty,overthinking,meaninglessness" },

  { slug: "loss", category: "life-challenges", title: "Carrying What We Loved",
    problem: "I lost someone or something dear, and the grief feels unbearable.",
    tags: "loss,grief,death,mourning,sadness,goodbye",
    wisdom: "Grief is the price of love, and it is a price worth paying. The depth of your sorrow is a measure of the depth of your bond. You are not broken for grieving — you are loving someone who is no longer here to receive it.\n\nThere is a cruel myth that grief should follow a tidy schedule, that healing means returning to who you were. But you do not get over a great loss; you grow around it. The loss remains; your life slowly grows larger to hold it.\n\nWhat you loved does not vanish entirely. It lives on in how it changed you, in the values it left behind, in the way you now move through the world. To carry someone forward is its own quiet form of keeping them.",
    shift: "You do not \"get over\" loss — you grow around it. Grief is not a problem to solve but love with nowhere to go.",
    action: "Honor what you lost today in one small way — a memory written down, a ritual, a word spoken aloud.",
    questions: ["What is my grief telling me about what I loved?", "How might I carry this forward rather than leave it behind?", "What do I need to give myself permission to feel?"],
    related: "regret,meaninglessness,loneliness,uncertainty" },

  { slug: "meaninglessness", category: "life-challenges", title: "When Nothing Seems to Matter",
    problem: "I feel empty, as if nothing I do has any meaning at all.",
    tags: "meaninglessness,emptiness,nihilism,purpose,void,depression",
    wisdom: "The feeling that nothing matters is not a discovery of truth — it is often a symptom of exhaustion, disconnection, or a self turned too far inward. The void you sense is not proof that meaning is absent, but that the channels through which meaning usually flows have been blocked.\n\nMeaning is not handed to you by the universe; it is generated through engagement — through love, work, creation, contribution, and care. When you feel nothing matters, the path back is rarely through more thinking. It is through small acts of involvement that remind you that you can affect the world and be touched by it.\n\nYou do not need to solve the cosmic question of why anything matters. You only need to find the next thing that matters to you, however small, and let your participation slowly rekindle the sense that you belong to life.",
    shift: "The sense that nothing matters is usually a signal of disconnection, not a truth about reality. Meaning returns through engagement, not analysis.",
    action: "Do one small act of genuine engagement today — help someone, create something, or care for a living thing.",
    questions: ["Is this emptiness a truth, or a signal of disconnection?", "When did I last feel genuinely engaged with something?", "What is one small thing that still matters to me?"],
    related: "purpose,identity-crisis,loss,fear-of-future" },

  // A few extra cross-cutting struggles to broaden the library / search
  { slug: "anxiety", category: "life-challenges", title: "The Body That Sounds the Alarm",
    problem: "My anxiety makes me feel like something terrible is about to happen.",
    tags: "anxiety,panic,fear,worry,nervous,stress",
    wisdom: "Anxiety is not your enemy, though it rarely feels like a friend. It is an ancient alarm system, built to protect you from danger — and in the modern world it often fires when there is no lion, only a deadline, a message, a what-if. The alarm is real even when the threat is not.\n\nThe more you fight anxiety, the louder it grows, because fighting it tells your nervous system that something truly is wrong. Paradoxically, the way through is often to make room for it — to let the wave rise, crest, and fall, knowing it always falls.\n\nYou are not your anxiety. You are the calm awareness that notices it. From that quieter place, you can act with care rather than be ruled by alarm.",
    shift: "Anxiety is a misfiring alarm, not a prophecy. The wave always crests and falls if you let it.",
    action: "When anxiety rises, breathe out slowly for longer than you breathe in, and name three things you can see right now.",
    questions: ["Is this a real threat, or a misfiring alarm?", "What helps the wave pass, rather than fighting it?", "Who am I beneath the anxiety, noticing it?"],
    related: "overthinking,fear-of-future,uncertainty,exam-stress" },
];

export const REFLECTIONS = [
  { date: "2026-06-02", thought: "The cave you fear to enter holds the treasure you seek. What you avoid is often exactly where your growth waits.",
    author: "— The Archive", question: "What is one thing I have been avoiding that might actually be the door to what I want?",
    challenge: "Spend ten minutes today on the one task you have been putting off — no need to finish, only to begin." },
  { date: "2026-06-01", thought: "You are not required to set yourself on fire to keep others warm. Rest is not a betrayal of your responsibilities; it is part of them.",
    author: "— The Archive", question: "Where am I giving more than I can sustainably afford to give?",
    challenge: "Say a small, kind \"no\" to one thing today that drains you without serving you." },
  { date: "2026-05-31", thought: "Comparison is the thief of joy because it measures your private struggle against another's public highlight.",
    author: "— The Archive", question: "Whose life am I comparing mine to, and what am I forgetting about theirs?",
    challenge: "Notice each comparison today and gently return your attention to your own path." },
  { date: "2026-05-30", thought: "Between stimulus and response there is a space. In that space lies your freedom and your power to choose.",
    author: "— The Archive", question: "Where in my life am I reacting when I could be choosing?",
    challenge: "Pause for one full breath before responding to something that provokes you today." },
  { date: "2026-05-29", thought: "You do not have to see the whole staircase. You only have to take the first step.",
    author: "— The Archive", question: "What first step have I been waiting to feel ready for?",
    challenge: "Take one small, concrete step toward something you have only been thinking about." },
];
